name: Placeholder Test Action

on:
  workflow_dispatch:

env:
  packageName: "com.vrchat.ClientSim"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3